directories:
  aggregate_directory: aggregate
  app_directory: /Users/jwbullard/Library/CloudStorage/OneDrive-TexasA&MUniversity/Documents/Projects/Modeling/VCCTL-THAMES-SPRING/vcctl-gtk/src
  bin_directory: bin
  data_directory: data
  database_directory: database
  logs_directory: logs
  materials_directory: materials
  operations_directory: operations
  particle_shape_set_directory: particle_shape_set
  temp_directory: temp
  usr_directory: usr
logging:
  backup_count: 5
  console_level: INFO
  date_format: '%Y-%m-%d %H:%M:%S'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_file: vcctl.log
  log_function_timing: false
  log_sql_queries: false
  log_to_console: true
  log_to_file: true
  logger_levels:
    VCCTL: INFO
    VCCTL.Config: INFO
    VCCTL.Database: WARNING
    VCCTL.Services: INFO
    VCCTL.UI: INFO
  max_file_size: 10
  performance_logging: false
materials:
  aggregate_absorption_default: 1.0
  air_density: 0.001225
  cement_composition_limits:
    alkalis:
    - 0.0
    - 0.01
    c2s:
    - 0.0
    - 0.4
    c3a:
    - 0.0
    - 0.15
    c3s:
    - 0.0
    - 0.8
    c4af:
    - 0.0
    - 0.2
    gypsum:
    - 0.0
    - 0.1
    so3:
    - 0.0
    - 0.04
  cement_default_fineness: 370.0
  cement_default_psd: cement141
  cement_default_specific_gravity: 3.2
  ch_specific_gravity: 2.24
  coarse_aggregate_default_specific_gravity: 2.7
  csh_specific_gravity: 2.1
  ettringite_specific_gravity: 1.78
  fine_aggregate_default_specific_gravity: 2.65
  fly_ash_default_specific_gravity: 2.77
  inert_filler_default_specific_gravity: 3.0
  limestone_specific_gravity: 2.71
  monosulfate_specific_gravity: 2.02
  psd_limits:
    cement_d10:
    - 1.0
    - 5.0
    cement_d50:
    - 10.0
    - 30.0
    cement_d90:
    - 30.0
    - 100.0
    fly_ash_d50:
    - 5.0
    - 50.0
    slag_d50:
    - 8.0
    - 45.0
  quartz_specific_gravity: 2.65
  silica_fume_default_specific_gravity: 2.2
  slag_default_specific_gravity: 2.87
  water_density: 0.997
  water_specific_gravity: 1.0
simulation:
  available_particle_shapes:
  - sphere
  - ellipsoid
  - irregular
  - angular
  checkpoint_interval: 100
  compression_enabled: true
  default_aggregate_shape: sphere
  default_aggregate_volume_fraction: 0.7
  default_air_content: 0.05
  default_cement_shape: sphere
  default_diffusivity_water: 2.3e-09
  default_flocculation_degree: 0.0
  default_hydration_cycles: 2000
  default_maximum_aggregate_size: 25.0
  default_permeability: 1.0e-18
  default_poissons_ratio_aggregate: 0.2
  default_poissons_ratio_cement: 0.25
  default_resolution: 1.0
  default_system_size: 100
  default_temperature: 25.0
  default_water_binder_ratio: 0.4
  default_youngs_modulus_aggregate: 70000.0
  default_youngs_modulus_cement: 20000.0
  elastic_convergence_tolerance: 1.0e-08
  elasticity_enabled: true
  flocculation_enabled: false
  hydration_convergence_tolerance: 1.0e-06
  max_aggregate_volume_fraction: 0.85
  max_air_content: 0.15
  max_flocculation_degree: 1.0
  max_hydration_cycles: 100000
  max_iterations: 1000
  max_resolution: 10.0
  max_system_size: 1000
  max_worker_threads: 4
  memory_limit_per_simulation: 2048
  min_resolution: 0.1
  output_format: hdf5
  parallel_processing_enabled: true
  save_intermediate_results: false
  transport_enabled: true
user:
  app_directory: /Users/jwbullard/Library/CloudStorage/OneDrive-TexasA&MUniversity/Documents/Projects/Modeling/VCCTL-THAMES-SPRING/vcctl-gtk/src
  auto_save_enabled: true
  auto_save_interval: 300
  cache_enabled: true
  confirm_destructive_actions: true
  max_recent_projects: 10
  max_worker_threads: 8
  memory_limit_mb: 4096
  particle_shape_sets:
  - sphere
  - ellipsoid
  recent_projects: []
  show_welcome_dialog: true
